/** Shared public information; keep platform settings and navigation distinct. */
export function PublicMobileInformation({ page }: { page: "privacy" | "help" }) {
  if (page === "help") return <>
    <section><h2>Using the iPhone and iPad app</h2><p>The iOS app is being prepared for release. Its navigation includes Home, Walks, People, Map and More. Browser installation instructions above apply to the website.</p><p>Location and notifications are optional. You can change permission in iOS Settings. Device reminders use work already available on your device; remote notifications also require a working connection and an enabled delivery service. Neither guarantees delivery. SMS is not available in this release.</p></section>
    <section><h2>Request account deletion on iOS</h2><p>Open <strong>More → Settings → Delete account</strong>. The deletion option is also available when your account has no church invitation or its workspace cannot be opened. Reconnect before submitting. If you use Sign in with Apple, confirm the same Apple account when prompted.</p><p>The proposed release process allows up to 30 days for the operator to remove your account and associated personal data and email completion confirmation. A request receipt means the request was recorded; it does not mean deletion has finished. Your account remains available until processing. This process must be activated and rehearsed before public release.</p><p>Share pending work first. Deletion does not uninstall the app or erase offline copies and exports on your devices. Keep the request reference if you contact support; never send your password or sign-in codes.</p></section>
  </>;
  return <>
    <section><h2>iOS permissions and services</h2><p>The iPhone and iPad app stores account sessions, prepared church records and pending work on the device for offline use. The same access, export and device-protection limits described above apply.</p><p>When you use the map’s locate control, iOS can request location permission to display your position. The app does not implement background location tracking. Map providers receive requests for the area displayed; address searches send your query to the configured search provider.</p><p>Optional device reminders are scheduled on the device. When remote notifications are enabled, the service stores an Apple push device token associated with your account and sends notifications through Apple Push Notification service. Notification text avoids neighbor names and care notes. Turn notifications off in the app or iOS Settings.</p><p>Sign in with Apple provides an account identifier and may provide a name and email, including a private relay address. For an Apple-linked deletion request, the app requests fresh authorization so the server can verify the same Apple identity and revoke its authorization. Authorization codes and Apple tokens are used for this exchange and are not stored by the deletion service.</p></section>
    <section><h2>iOS account deletion</h2><p>The app includes a Delete account option in Settings and on the screens for missing church access. The proposed process requires the operator to remove the account and associated personal data within 30 days and email confirmation. Request records track processing; submitting a request alone does not erase records.</p><p>Before public release, the operator must approve and verify how shared church records, history, backups and legally required retention are handled. Any legally required exception must be explained to the requester. Copies already exported or held offline require separate handling; deleting an account cannot remotely erase them.</p></section>
  </>;
}
